### Reference1: https://hudi.blog/vscode-rest-client/
### Reference2: https://blog.jiniworld.me/144

@server = http://localhost:8000

### 메인 페이지 조회
GET {{server}}

### 전체 선수 조회
GET {{server}}/players

### 특정 선수 조회
GET {{server}}/players/1

### 선수 추가
POST {{server}}/players
Content-Type: application/json; charset=UTF-8

{
  "name": "손흥민",
  "age": 30,
  "team_id": 2
}

### 특정 선수의 소속 팀 변경
PATCH {{server}}/players/1/team
Content-Type: application/json; charset=UTF-8

{
  "team_id": 1
}

### 특정 선수 삭제 (Player, Profile 연쇄 삭제)
DELETE {{server}}/players/2

### 전체 팀 조회
GET {{server}}/teams

### 이름 순으로 전체 팀 조회
GET {{server}}/teams?sort=name_asc

### 이름으로 팀 검색
GET {{server}}/teams?search=KT

### 특정 팀 조회
GET {{server}}/teams/4

### 특정 팀의 모든 선수 조회
GET {{server}}/teams/1/players

### 모든 경기 조회
GET {{server}}/teamgames
