@server=http://localhost:8000
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImxlYWRlciIsImlhdCI6MTcyNjc1Njk4MX0.sgeGgDW7ud7TRG3x6gp3HY7NXYRiqS0aTshrZ0oXnNA
### 로그인 요청
POST {{server}}/login
Content-Type: application/json; charset=UTF-8

{
    "id": "leader", 
    "pw": "1234"
}

### 토큰 검증 요청
POST {{server}}/token
Content-Type: application/json; charset=UTF-8
Authorization: Bearer {{authToken}}
